baseurl: "https://jhuang.netlify.app/"
title: "Dreaming time - a blog by Ji Huang"
author: "Ji Huang"
canonifyurls: true
languageCode: en-us
theme:
    - PaperMod
enableEmoji: true

params:
    env: production
    title: "Dreaming time"
    description: "Dreaming time - a blog by Ji Huang"
    author: "Ji Huang"
    hideSummary: true
    ShowPageNums: true
    defaultTheme: auto
    disableThemeToggle: false
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowShareButtons: false
    ShowToc: false
    disableSpecial1stPost: true
    mainSections:
        - blog
    assets:
        favicon: "images/favicon1.png"

markup:
    goldmark:
        renderer:
            unsafe: true

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: /about/
          weight: 2
        - name: Twitter
          url: https://twitter.com/ji_timedreamer
          weight: 4
        - name: Subscribe
          url: /index.xml
          weight: 5
